package eu.steffo.cleaver.logic.config;

/**
 * A configuration generated by a {@link eu.steffo.cleaver.gui.panels.rows.option.OptionRow OptionRow} to configure a step of a
 * {@link eu.steffo.cleaver.logic.job.ChopJob ChopJob}.
 */
public interface IConfig {
    /**
     * Get the string representation of the step, to be displayed in the <i>Operations</i> column of the
     * {@link eu.steffo.cleaver.gui.panels.JobsTablePanel JobsTablePanel}.
     *
     * @return The string to be displated.
     */
    @Override
    String toString();
}
