package eu.steffo.cleaver.logic.config;

/**
 * A {@link IConfig} generated by a {@link eu.steffo.cleaver.gui.panels.rows.option.CryptRow CryptRow}.
 */
public interface ICryptConfig extends IConfig {
}
