package eu.steffo.cleaver.logic.config;

/**
 * A {@link IConfig} generated by a {@link eu.steffo.cleaver.gui.panels.rows.option.CompressRow CompressRow}.
 */
public interface ICompressConfig extends IConfig {
}
